Add comment to exclude history.h
##Error##
`REPL.c:4:10: fatal error: 'editline/readline.h' file not found`

##Solution##
There is a common error on including `<editline/history.h>`. The solution is to remove it given many users on MacOS X that doesn't have the lib. 

##Reference##
https://stackoverflow.com/questions/22886475/editline-history-h-and-editline-readline-h-not-found-working-on-osx-when-trying